name: Build and Release Electron Forge App

on:
  push:
    tags:
      - v*    # Triggers on version tags like v1.0.0

permissions:
  contents: write   # Required for creating releases and uploading assets

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 22 LTS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Make distributables (Electron Forge)
        run: npm run make

      - name: Archive distributables
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: out/make/

      - name: Create GitHub Release and Upload Assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/make/**/*.zip
            out/make/**/*.deb
            out/make/**/*.rpm
            out/make/**/*.exe
            out/make/**/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
